<a href="https://colab.research.google.com/github/sriram-gg/ML_3/blob/main/sriram700762460.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Create random vector of size 15 with integers in range 1-20
random_vector = np.random.randint(1, 21, size=15)

# Reshape the array to 3 by 5
reshaped_array = random_vector.reshape(3, 5)

# Print array shape
print("Array shape before replacing max:", reshaped_array.shape)

# Replace the max in each row by 0
reshaped_array[np.arange(len(reshaped_array)), np.argmax(reshaped_array, axis=1)] = 0

print("Array after replacing max in each row by 0:")
print(reshaped_array)


Array shape before replacing max: (3, 5)
Array after replacing max in each row by 0:
[[ 1 18 16  0  9]
 [11  7 12  1  0]
 [ 9  0  8  2 15]]


In [2]:
import numpy as np

# Create a 2-dimensional array of size 4 x 3 with 4-byte integer elements
array = np.random.randint(low=-1000, high=1000, size=(4, 3), dtype=np.int32)

# Print the shape, type, and data type of the array
print("Shape of the array:", array.shape)
print("Type of the array:", type(array))
print("Data type of the array:", array.dtype)

# Define the square array
array = np.array([[3, -2], [10, 0]])

# Compute eigenvalues and right eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(array)

# Print the eigenvalues
print("\nEigenvalues:")
print(eigenvalues)

# Print the right eigenvectors
print("\nRight Eigenvectors:")
print(eigenvectors)

Shape of the array: (4, 3)
Type of the array: <class 'numpy.ndarray'>
Data type of the array: int32

Eigenvalues:
[1.5+4.21307489j 1.5-4.21307489j]

Right Eigenvectors:
[[0.13693064+0.38459936j 0.13693064-0.38459936j]
 [0.91287093+0.j         0.91287093-0.j        ]]


In [3]:
import numpy as np

# Define the array
array = np.array([[0, 1, 2], [3, 4, 5]])

# Compute the sum of the diagonal elements
diagonal_sum = np.trace(array)

# Print the sum of the diagonal elements
print("Sum of the diagonal elements:", diagonal_sum)

Sum of the diagonal elements: 4


In [4]:
import numpy as np

# Original array
array_3x2 = np.array([[1, 2], [3, 4], [5, 6]])
array_2x3 = np.array([[1, 2, 3], [4, 5, 6]])

# Reshape to 2x3 and 3x2
reshaped_array_2x3 = np.reshape(array_3x2, (2, 3))
reshaped_array_3x2 = np.reshape(array_2x3, (3, 2))

# Print the reshaped arrays
print("Original array 3x2:")
print(array_3x2)
print("Reshaped to 2x3:")
print(reshaped_array_2x3)
print("Original array 2x3:")
print(array_2x3)
print("Reshaped to 3x2:")
print(reshaped_array_3x2)


Original array 3x2:
[[1 2]
 [3 4]
 [5 6]]
Reshaped to 2x3:
[[1 2 3]
 [4 5 6]]
Original array 2x3:
[[1 2 3]
 [4 5 6]]
Reshaped to 3x2:
[[1 2]
 [3 4]
 [5 6]]
